apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crb
subjects:
- kind: ServiceAccount
  name: sa
  apiGroup: ""
  namespace: default
roleRef:
  kind: ClusterRole
  name: cr
  apiGroup: rbac.authorization.k8s.io

