apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k-network
  namespace: argocd
spec:
  project: otus
  source:
    repoURL: https://github.com/Kuber-2025-02OTUS/sychevnikova_repo.git
    targetRevision: main
    path: kubernetes-networks
  destination:
    server: https://kubernetes.default.svc
    namespace: homework
  syncPolicy:
    automated:
      enabled: false
    syncOptions:
    - CreateNamespace=true
